### ISSUE TITLE
Tic manyullyn tool rod

### ISSUE THREAD

**Issue by Tyron393** [FTBTeam/FTB-Continuum#136]
1.1.0
When using manyullyn tool rods it should give the item more durabilty by 250 however using it will decrease the the durabilty by qute a large ammount

**Comment by Divran** [comment]
Most likely this is because that tool rod has a handle modifier of 0.5. The base durability of the tool is multiplied by this number. This is why it's best to find a tool rod that has a modifier above 1, like ardite for example. Ardite gives -200 and has a multiplier of 1.4, if your tool is a hammer, -200 is nothing compared to a 40% increase in durability. Another great choice is cobalt, with a multiplier of 0.9. Another one is bronze, with a multiplier of 1.1. Bronze also gives you the Dense passive ability, which is amazing, especially for hammers.
