### ISSUE TITLE
Apiary Eats energy bee after latest update

### ISSUE THREAD

**Issue by Valerate** [FTBTeam/FTB-Continuum#153]
* **Modpack Version**: 1.2.0

* **Issue**: When I put eneegy bee into a apiary, it says its missing flowers for a few seconds before deleting the queen. The apiry is connected with a RFtool power relay into 4 industrial Apiaris from Gendustry

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/4a5f26cf

* **Is it Repeatable?**: Yes, Ive lost three queens now

* **Mod/s Affected**: Forestry Apiary/ Career bees and/or RfTools enegy relay

* **Known Fix**: None atm, trying to downgrade

**Comment by Valerate** [comment]
Seeing that both Forestry and RFtools energy was updated from 1.1 -> 1.2 I suspect one of these is responsible.

**Comment by lhw** [comment]
Most likely RFTools. It also causes a server crash with industrial apiary when I updated to 1.2.0 from 1.0.2.
The bees in your case were most likely removed because of the forge option to remove erroring entities.
https://paste.feed-the-beast.com/view/c3dd8e0d
Second one is adding the bee into the apiary with forge setting to remove erroring entities.
https://paste.feed-the-beast.com/view/4addb93b

**Comment by lhw** [comment]
This is already fixed in rftools: McJtyMods/RFTools#1773

**Comment by lhw** [comment]
This bug has been fixed by the 1.2.1 update and can be closed.

**Comment by Valerate** [comment]
Done :)
