### ISSUE TITLE
Advanced RF Storage dosn't count RF/t with crafting

### ISSUE THREAD

**Issue by lglare** [FTBTeam/FTB-Continuum#239]
* **Modpack Version**: 1.3.1

* **Issue**: Advanced RF Storage not working

* **Link to Log or Crash File Paste**: not crash

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Efab

* **Known Fix**: dont know

I tried to craft Energy Condenser with efab crafting system thats need 1M RF/t.
then i crafted 1000 Advanced RF Storages and placed it.
but infomation with crafting grid says "1000000RF/t needed but only 2200 possible".
(2200 means already placed 4 RF Storages and 4 RF Controls.)
is it issue isn't it?

**Comment by lglare** [comment]
next, i tried 4000 RF Storages and placed it.
but count only about 23000 RF/t.

In both case,i got huge lag.

**Comment by Morganamilo** [comment]
Not in game so I can't check myself. When you hover over the gearbox it says you can use up to four. Does it also say this on rf storage?

**Comment by tfox83** [comment]
Duplicate to #144

**Comment by zenoran** [comment]
Has anyone even tested this?  Advanced Storage isn't even working in the pack yet which is the only way to get that amount of power... Even the concept of 1000 advanced blocks sounds like it's screaming for bugs/lag with efab.  Am I missing something here or was this just not even considered to be obtainable?

**Comment by aaronhowser1** [comment]
The Advanced Storage was made after Continuum 1.0 came out

**Comment by zenoran** [comment]
Ya but it hasn't worked until the most recent version which isn't even in a Continuum update yet which kind if means it was never tested? Or was it tested with regular blocks? Not at my computer right now but regular provide 250 rf/t? So u have to add 4,000 blocks to your efab to make this work?

Am I missing something here? 

I consider myself to be very open-minded to this pack. I grinded everything to this point never criticising anything and even defending it on forums. Now coming to this point I am just scratching my head. All of that grind to come to "end game" which is horribly nerfed/stripped (most of PE) and gated behind silly things like adding 1,000 blocks to your efab to craft 1 recipe? Honestly I don't even know what the block is going to help with because we can't even duplicate matter since it doesn't have an EMC value.

I am just wondering if I'm missing something. Is this a wild goose chase or just not properly thought out since it's the end of the pack and not many have made it here yet. I guess I'll load a test world and see if it even works because I highly doubtful anyone tested it. Anyone who built an efab to test it would clearly see how silly it is and come up with an alternative.

**Comment by aaronhowser1** [comment]
I'm 90% certain you're supposed to use a Power Optimizer for the Energy Condenser, that removes the RF/t limit entirely. It uses RF as fast as you can provide it no matter how many Storages you have. The recipe was finalized before the Advanced Storage was a thing. You aren't expected to add thousands of any block to your EFab at all. I think you can dupe everything needed to make Matter, just not the Matter itself.

**Comment by zenoran** [comment]
Okay I personally tried it with the power optimizer and it didn't work. It just sat there and made noise but no progress was counting down. No error. No power was being consumed not any fluid. I assumed it was because I didn't have the storage blocks to technically support it and that's where I just gave up without doing some more research.

If it's supposed to work with power optimizer that is what I wanted to confirm so I could troubleshoot other things. Maybe the physical battery storage and/or conduits to support the 1m/tic I'll have to play around with in a test world to get it working.

**Comment by aaronhowser1** [comment]
Did it also have regular RF Storages on it? Like 5 regular Storages, some Controls, and a Power Optimizer should work from memory. I personally haven't gotten there yet though.

**Comment by zenoran** [comment]
Ya it seems like it was the regular storage blocks weren't cutting it. I switched to 1 advanced and it started working. I'm using new efab release though so I guess it wouldn't work at all without advanced. Maybe something to do with the buffer in the blocks since advanced has 1m buffer? Could possibly work with regular if u had 10 of them for 100k x 10 but not sure.

It's cool the actual rf/t from battery doesn't seem to matter, it just sucks as much as it can and counts down slower. I didn't actually make it yet in my survival world, still grinding a few materials, but it seems doable.
