### ISSUE TITLE
Server wont update

### ISSUE THREAD

**Issue by TheGameGeek** [FTBTeam/FTB-Continuum#29]
* **Modpack Version**: 1.0.2

* **Issue**: server wont launch

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/7537ba7f

* **Is it Repeatable?**: yes

* **Description of error**: When i tried update the server even with a clean install (redoing the server) it keeps on crashing and never launches and this is the crash report

**Comment by jc2xs** [comment]
So can you provide some details on the server itself?  Specifically how much physical RAM do you have?  Please look at line 394 of your crash log.  You are running both -Xmx and -Xms at 8GB.  It should be more like -Xms512M and -Xmx8G and that is assuming you have more than 8GB of RAM on the server.  BTW: I'm running -XmX7G with no issues on mine and my server has 32GB of physical RAM.

Also another little tidbit since this is the server watchdog error.  Edit the server.properties file and change max-tick-time to -1 instead of 6000.

BTW: I've had no problem updating my server running Ubuntu Linux.  I started with 1.0.0 when it was released and updated to 1.0.1 yesterday and 1.0.2 today.  No issues so far.

**Comment by TheGameGeek** [comment]
Alright thank you i never eddited the -Xmx thats what it came with. The server is a 8GB server.

**Comment by 016Nojr** [comment]
Did you try again @TheGameGeek?

**Comment by TheGameGeek** [comment]
Yes @016Nojr if i remember correctly all i did was change the max-tick-time to -1 and it loaded right up
