### ISSUE TITLE
Cyanite / blutonium comb products messed up

### ISSUE THREAD

**Issue by Hypermobile** [FTBTeam/FTB-Continuum#301]
Version: 1.3.1
Issue: Cyanite combs have 100% chance of blutonium grains in Cent. Separator, but 25% chance of cyanite grains in the forestry centrifuge. Same applies to blutonium combs producing 100% chance of cyanite grains in the separator and 25% chance of the correct blutonium grains in the centrifuge.
Log or crash file: None
Repeatable: Yes
Mods affected: Thermal Expansion, Binnie's Extra Bees, Forestry
Known fix: None from me

**Comment by tfox83** [comment]
Fixed in 1.4.0

**Comment by Jadoz** [comment]
This is not fixed in 1.4.1. Easiest to recreate by placing cyanite comb in Thermal Expansion Centrifugal Separator. Cyanite comb gives Blutonium grains at 100% rate. Need to switch the Blutonium and Cyanite comb recipes in this machine and probably reduce grains drop % to 25 to match Forestry machine.

**Comment by aaronhowser1** [comment]
I think that these bees got replaced with custom bees, so you might need to make those instead of the ones you already have.
