### ISSUE TITLE
Solar System planets missing and Warp Controller not working in multiplayer

### ISSUE THREAD

**Issue by hankjordan** [FTBTeam/FTB-Continuum#304]
* **Modpack Version**: 1.3.1

* **Issue**: Solar system planets missing, no artifact planets discoverable

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/raw/9c267924

* **Is it Repeatable?**: Yes, only occurs in multiplayer(?). Reinstalled and still occurred.

* **Mod/s Affected**: Advanced Rocketry

The advanced rocketry planetdefs.xml has all of the planets in the solar system marked as 'isKnown'. Still nothing on the warp controller. Works in single player. Bringing the world file over from single player doesn't fix the issue. I tried to search for multiple different artifact planets many times, even turned the discovery rate up to 100%. Still couldn't find anything. The quests for advanced rocketry were done out of order (made space station before visiting the moon).

![sol](https://user-images.githubusercontent.com/29737477/42304366-df7a378e-7ff3-11e8-9c7d-4b38aaa8bdcb.PNG)
This is what my Solar System looks like.

**Comment by aaronhowser1** [comment]
Do other solar systems work? IIRC only Sol should have the planets known by default. Could you try turning the server's `B:resetPlanetsFromXML` to true maybe? That's in \config\advRocketry\advancedRocketry.cfg

**Comment by paulbacks** [comment]
i have the same issue. 
changing the B:resetPlanetsFromXML to "true" does not work, it auto resets to false.

**Comment by EscolarProgramming** [comment]
I'm playing MP too, and there work all planets fine. In the solar system Sol I can see the earth, and in the solar system "ETech Conglomerate" there is the planet Ionite (quest "Land of the Red Blood"). At the moment I haven't discovered more planets, so I can't tell you if other planets are buggy.

**Comment by hankjordan** [comment]
@aaronhowser1 No planets shown in any solar system. Planets outside of Sol are correctly marked as isKnown false. Tried the config change and restarted, nothing happened.
@paulbacks I think that's intentional functionality.

Changing B:resetPlanetsFromXML to true and deleting the AdvRocketry world folder didn't work.
Also changed B:planetsMustBeDiscovered to false, but it didn't work.

Earth can only be discovered for me when I program a chip from the guidance computer and click the 'Program from chip' on the warp controller

**Comment by tfox83** [comment]
known issue at this time without a universal fix that I can implement

**Comment by Neomania** [comment]
This bug is still present, are there any detailed workarounds? I've seen something vague about setting 'isKnown' to false and rediscovering them manually, in #464, but that hasn't worked for me. I tried generating a new world with the latest modpack version, no dice; the only thing I haven't tried yet is a completely fresh client and server in an isolated environment.

If this is present on all servers, I think the bug should be escalated in some way or at least made common knowledge; it's kind of damning for my own server to have been working towards rocketry for a few months, only to find that it's broken.

Has anyone been able to successfully travel to planets in multiplayer? Some knowledge of the differences between broken and working servers would be useful, I think.

P.S. If it helps at all, it seems the planetDefs.xml in the singleplayer games (where the warp controller seems to work fine) is different and contains some extra items compared to the config that comes with the server.

**Comment by Neomania** [comment]
For anyone looking into this in future, a workaround I've found so far is to set 'B:planetsMustBeDiscovered' to false, the key being to do so in **both** the server and client configs. Admittedly, this makes all planets visible, but given that it's just an RNG grind to find them and you still need the artifacts to warp to them, I think it's an acceptable shortcut.

**Comment by Convex6** [comment]
Hi Folks,   I am having the same problem.   Did all the things above.  No joy.   In addition, I removed artifact lines fron planetdefs.xml, no joy.   I completely rewrote the same file and put it in the three places it resides on server,  no joy.   The only thing that did work is when I changed number of planets from 0 in Sol to 9.   Then, It created 9 more planets, which I could see in the warp controller and could travel to.   However, these 9 new planets were the only ones visible.  I could have the gone back to the planetsdef.xml and renamed them from “Sol16,” and the fool the warp controller.  But it would now be out of agreement with the planet selector.   Still no joy.   It is hard for me to accept that there is no one smart enough to fix this.  It almost makes me want to get a Java editor, compiler and have a go.   I’ll keep at it and post results here.  Thanks for everyone’s posts.  They help.  

Convex6
