### ISSUE TITLE
Crash while launching Rocket to Luna with satellite (unable to progress)

### ISSUE THREAD

**Issue by Ravalli03** [FTBTeam/FTB-Continuum#348]
* **Modpack Version**: 1.4.1

* **Issue**: Game crashes when launching to Luna with satellite. Unable to progress pack do to bug.

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/f8101e3c

* **Is it Repeatable?**: Yes, game will no longer load, crashes.

* **Mod/s Affected**: Advanced Rockety

* **Known Fix**: Unknown, issue was also opened here https://github.com/zmaster587/AdvancedRocketry/issues/1354

**Comment by ZeekDaGeek** [comment]
I had this issue on my server, seemed the solution was sending up rockets without a seat on them. Advanced Rocketry doesn't like you riding a rocket with a satellite.

Look into the http://65.78.115.159:8000/AdvancedRocketry/blocks/RocketMonitoringStation.php in order to launch unmanned rockets.

To get your world to load you can turn on forge's "removeErroringEntities" option.

**Comment by Ravalli03** [comment]
ok, will give it a try. Thank you very much for the help

**Comment by DestinyPlayer** [comment]
If you look at issue 1354, the author of the Advanced Rocketry mod already implemented a fix in the newest version. It had nothing to do with having a seat, but instead a mixup of variables.

**Comment by aaronhowser1** [comment]
Link: zmaster587/AdvancedRocketry/issues/1354

**Comment by tfox83** [comment]
Fixed in 1.5.0
