### ISSUE TITLE
Immersive Engineering - Diesel Generator RF Output

### ISSUE THREAD

**Issue by WolfChylde** [FTBTeam/FTB-Continuum#41]
Hey there.

I was curious if it was intended that the diesel generator using an immersive petroleum distillation tower and pump jack was intended to not be able to provide enough power to cover the cost of the generating the diesel in the first place.

It appears the diesel generator rf/t was reduced to 1024 instead of 4096:
```
# The Flux per tick that the Diesel Generator will output. The burn...
I:dieselGen_output=1024
```
None of the other Immersive Petroleum modifiers were changed though:
```
# The Flux the Pumpjack requires each tick to pump, default=1024
I:pumpjack_consumption=1024
```
```
# A modifier to apply to the energy costs of every Distillation Tower recipe, default=1
D:distillationTower_energyModifier=1.0
```
* **Modpack Version**: 1.02

* **Issue**: Power generation from IE Diesel generator isn't enough to power pump jack/distillation tower.

* **Mod/s Affected**: Immersive Engineer / Immersive Petroleum.

* **Known Fix**: If not intended to make the diesel generator running diesel from Immersive Petroleum useless, I believe you could quarter each of the values for the Immersive Petroleum machines. This would reduce the total RF generated by the diesel generator, while still allowing it to be functional. Pumpjack would consume 256/tick, and distillation energy modifier would be 0.25. Resulting in a surplus output I believe of around 512 rf/tick. Instead of the 2048 rf/tick it would normally generate.

```
# The Flux the Pumpjack requires each tick to pump, default=1024
I:pumpjack_consumption=256
```
```
# A modifier to apply to the energy costs of every Distillation Tower recipe, default=1
D:distillationTower_energyModifier=0..25
```

**Comment by Xavion3** [comment]
Bio diesel is also affected to note, if less severe. Produces 4x less than normal but costs the same, so you make about 1.8x the power invested now, not the 7x or so of normal recipes.

I've noticed that in general due to these it's far more effective to never build the diesel generator and just build a dozen compression dynamos or semifluid generators or similar with the same fuel.

**Comment by mtimyself** [comment]
I have followed the Quests and got into Immersive Petroleum.
100s of Iron later and the only thing I paid for was the privilege to burn energy for lubricant and bitumen.
Since this is the only energy production suggested by the quest book at that stage this can easily be considered a major progression break.

**Comment by StoneLegion** [comment]
I must comment that I'm fine with nerfing crafting, etc but Nerfing Numbers has ruined the enjoyment of this pack made devs brains melt because people complaining on their discords. Please consider fixing this up in a better method then breaking all the math / numbers.

**Comment by mtimyself** [comment]
It is worth mentioning that, while I usually do not like changing "invisible" numbers, the Engineers Manual does actually pull the values out of the config to display correctly in the book.
That is a nifty feature.
The recommended power generation being broken due to mathematical errors is less nifty.

**Comment by tfox83** [comment]
These changes have been made in dev, thank you for the feedback and suggestions
