### ISSUE TITLE
Fusion reactor uses more energy than it produces...

### ISSUE THREAD

**Issue by TrademarkTM** [FTBTeam/FTB-Continuum#446]
The TechReborn fusion reactor generates 131kRF/t for 1024 ticks, but requires 160MRF. Multiplying the values, you get `131000 * 1024` which is `134144000`, a loss of almost 30MRF. It's basically pointless to make it.

Even with that fixed, it would still be ridiculous - the best powercell can handle 2500RF/t, using 5 sides (12500RF/t) it would require at least 11 of them.

I'm not sure about how power should be generated in this modpack. Currently using Endergenics, the only reliable power source I've found. Extreme Reactors eats uranium, all the other ones generate very small amounts and fusion makes no sense.

**Comment by Proha5** [comment]
160MRF requeres only for starting (once).
Reactor will generate 131MFR per each tritium+detuterium.
Tritium and deuterium makes from water. I builded factory for creating infinity tririum+deuterium. The reactor works non-stop.
Fusion reactor is CHEAT. Infinity 131KRF/t. + 256Krf (from helium-3)
My powerbank can accept 80KRF/t. I lost 51KRF (131-80). But i don't worry, because energy is free.
My top tier ore miner works at max speed consuming 30-40Krf. For what i need more energy?
The modpack is extra easy. Start game is hard. But middle game is easy. (infinity energy, infinity any ore).
I'm bored. Now i reach rocketry..

Modpack developer, i have question. Endgame is harder? or easy too? Endgame requere tons energy and resources?

**Comment by TrademarkTM** [comment]
You're wrong. It consumes the energy (160M / 240M), and it's a loss.
I just tested, you end up producing 130M, but uses 160M (with deuterium + helium3). The same goes for deuterium + tritium.

Not sure what you're doing to make power, but it's not the fusion energy, for sure.

**Comment by modmuss50** [comment]
The idea with the fusion reactor is that once you get it going you keep it provided with resources so it does not need to restart using the 160M. Its not too hard to automate the resources required to keep it going.

If you want more power you can increase the size of the reactor.
