### ISSUE TITLE
quest book empty

### ISSUE THREAD

**Issue by Casperclone1** [FTBTeam/FTB-Continuum#460]
* **Modpack Version**: 1.4.1

* **Issue**: at some point when i opened my quest book i noticed all the tabs and text were gone i have no idea how this happend

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/0e0d0ca1

* **Is it Repeatable?**: i have no idea how it happend it just kinda happend

* **Mod/s Affected**: no mods are getting affected only the quest book

* **Known Fix**: i have no idea how to fix it

**Comment by aaronhowser1** [comment]
Use the command `/bq_admin default load`, that should give you the quests back. Did you do anything to the modpack since the last time you launched? Added any mods, updated it, changed configs, etc? A couple people have had this happen to them so far, I don't know what causes it.

I'm not sure if you'll get your completed quests will stay completed, in which case use the command `/bq_admin edit` and then open the chapter and click edit. After that, click the checkmark button on the right then click on the quests that you've completed to re-complete them.

**Comment by Casperclone1** [comment]
thanks for the help
