### ISSUE TITLE
SJ2 Flux-Infused JetPlate is not craftable

### ISSUE THREAD

**Issue by TONAU3** [FTBTeam/FTB-Continuum#518]
* **Modpack Version**: 1.6.0

* **Issue**: For Flux-Infused SJ2 Jetplate I need to craft Glowstone elevation unit. Then I need to craft Hardened signlum glass. To get it, i need Induction smelter that is not craftable

* **Link to Log or Crash File Paste**: It's useless

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 

* **Known Fix**: I think you know how to fix that

**Comment by LemADEC** [comment]
SimpleJetpack2 has 3 erroneous recipes for:
- Reinforced thruster requires the uncraftable Magmatic dynamo
- Hardened thruster requires the uncraftable Fluxed armor plating from SJ2 (only the Redstone arsenal variant is craftable)
Those 2 actually prevent players to upgrade their Jetpack beyond the first level (Leadstone).

- Glowstone evelation unit (filled) can be crafted from Tech Reborn rolling machine. However, since Induction smelter is disabled, Hardened signalum glass is uncraftable, hence Glowstone evelation unit (empty) can't be crafted. Consider updating the Glowstone evelation unit (empty) recipe or removing it so it's less confusing.

**Comment by gewoonnico** [comment]
I have provided a temporary fix for this in #531. Just in case some of you guys want to move on :)

**Comment by 016Nojr** [comment]
This has been fixed in a pack update coming in a few days
