### ISSUE TITLE
Crash when starting existing world

### ISSUE THREAD

**Issue by MickRemmerswaal** [FTBTeam/FTB-Continuum#556]
* **Modpack Version**: 1.6.0

* **Issue**: Crash when loading existing world

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/669b5b30

* **Is it Repeatable?**: Probably

* **Mod/s Affected**: journeymap, advancedRocketry

**Comment by snake-4** [comment]
Seems like in advancedRocketry's code DocumentBuilder can't read/parse the XML files. And it seems like it is caused by your XML files having BOM, In your case these XML files should be found at 
> C:/Users/Gebruiker/Documents/Curse/Minecraft/Instances/FTB Continuum/saves/Henkies/advRocketry

Open the XML files at this location via some program that can convert the file to UTF-8 for example Notepad++ and convert the file to UTF-8 or remove the BOM character

**Comment by MickRemmerswaal** [comment]
![image](https://user-images.githubusercontent.com/5969421/59031035-e31cd180-8862-11e9-8e92-14171f21c508.png)

This is how it looks like in Notepad++, I tried changing it to with BOM saving it and back to UTF-8 without BOM and saving it. restarted it and it still crashes on the XML file

**Comment by snake-4** [comment]
Oh the file is corrupted, if you don't have any world backups then create a new world and copy this file of the new world to overwrite this save file's planetDefs.xml
