### ISSUE TITLE
Modpack died?

### ISSUE THREAD

**Issue by rexlManu** [FTBTeam/FTB-Continuum#577]
Is this modpack death? It didnt receive any updates anymore. Many bugs that are exist over 6 months arent get fixed.

**Comment by rune-san** [comment]
Modpacks never die as longs as they are available to download. I agree the pack has not received updates in quite some time. That said, like most modpacks, this modpack is maintained by one person who gets paid little (if any) for his efforts. It is a labor of love that is available for you to enjoy (or not).

@tfox83 also maintains several packs for FTB, some of which have recently been updated (like FTB Revelation 2). If you're waiting for an update to this pack, you might enjoy trying some of the others. :)

**Comment by rexlManu** [comment]
Yea I love the work from ftb Team. I played every Pack from them and had much fun and enjoyed it to play to the end.

**Comment by ghost** [comment]
it's pretty much the same with each pack: someone of the team gets some ideas - creates a pack - and forgets about it pretty soon as there're to many other packs - wich also mostly forgotten as there's already ideas for a new pack - repeat until death
this is how most packs end up in this broken state without anyone able to fix (for some packs the community does great work and tries to keep them alive by providing fixes - but even these die out over the time)
for me it's this:
1) there're way to many mods to begin with - just stacking up 200+ mods doesn't make a good pack
2) tinkering with already broken mods and try to interlock them make them even more broken
3) not enough testing before releasing (this goes back to the mod-devs as they release broken mods without testing)
4) noone willing to long-term maintain thier packs
To break it first the mod authors have to get thier mods straight and fully bug free - THEN one could use a "stable" version to build a pack around it. Unless there's a massive change in the modding community to move from release pre-alpha crap to fully test and only release stable versions (and then, instead of go on maintain it and fix what ever comes up) this mess will continue on. Maybe first a stable Minecraft is needed (as it's a mess too) and someone should fix all the issues in forge (who ever started this crap don't know Java conventions - interfaces ARE NOT marked with a capital I) - and maybe, just maybe then, all could agree to some standardized version everyone is using - I guess MC dev have to die first.
